### ISSUE TITLE
Casting intermittently stopped

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#117]
I'm casting a Spotify playlist to a Chromecast group. Works great!! But intermittently the Music stops (happens once in the few hours / few times per day). 
Just pressing play and everything resumes. When it happens I see a Google Cast error in the log:
```
Logger: homeassistant.components.cast.media_player
Source: components/cast/media_player.py:388
Integration: Google Cast (documentation, issues)
First occurred: 20:21:01 (1 occurrences)
Last logged: 20:21:01

Failed to cast media http://192.168.178.47:8095/media_player.everywhere_57.flac. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
```
The error itself probably is unavoidable, but maybe a retry can be done when it happens.
Best 
Eric

**Comment by marcelveldt** [comment]
Sounds to me like a network hiccup ? I'm using this with cast too myself and I've never noticed it disconnecting, it just keeps playing for hours and hours. But I will keep an eye on it, maybe a bug that is recently introduced.

Maybe this happens when the cast group switches the group "master". I'll take a look if I can detect this happening and retry but not sure if that is possible.

**Comment by erkr** [comment]
> Maybe this happens when the cast group switches the group "master".

Hi Marcel 
I know this issue is already closed, but I performed some related test today using  v1.0.15. I casted to just one CC, not the group, for over 5 hours without any interruption. Your suggestion could be right, unless the change for this issue was already in the v1.0.15 version

**Comment by erkr** [comment]
Then the hick ups seem to be  group related, will test group casting  using v1.0.16 when released 👍👍👍
