### ISSUE TITLE
v1.0.15 - Spinning wheels on Albums, Artists and Tracks where Album art should be

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#131]
I'm seeing many spinning wheels on album art per the title. Strange thing is, in Albums if I click a spinning wheel for an album, it displays the album art correctly. There's no apparent log errors.

Album example:

![Image 009](https://user-images.githubusercontent.com/22878629/167744890-f47cfbf4-e76a-4eb5-a28d-4af964164d6a.jpg)

![Image 010](https://user-images.githubusercontent.com/22878629/167744902-bc2ee242-233c-41fc-ac42-ee8138ede66b.jpg)

Artists example:
![Image 012](https://user-images.githubusercontent.com/22878629/167745095-b651fb0c-e159-4b37-983d-7f80eeadb3eb.jpg)

![Image 013](https://user-images.githubusercontent.com/22878629/167745105-c5f7fac1-baeb-4ce1-a0d4-86094c3e248e.jpg)

Tracks example:

![Image 014](https://user-images.githubusercontent.com/22878629/167745638-6b8c6338-7803-402d-8471-e9b33550f9fe.jpg)

**Comment by marcelveldt** [comment]
A spinning wheel means that no image is available (yet) for a media item.
I will change that to some fallback image soon because the spinner is a bit confusing.


**artists**: image/metadata is always retrieved from metadata providers, as long as the artist is matched on musicbrainz.
**albums**: metadata is not retrieved in advance from metadata providers but lazy loaded. If you watch the full details (once) for an album it will fetch all metadata. In case of local files, we'll try to grab the image from the underlying tracks of the album (embedded image in ID3 tag).
**tracks**: same as albums but image is retrieved from embedded image in ID3 tag if present.

**Comment by vk2him** [comment]
@marcelveldt - interesting thanks. I've noticed I have hundreds of .m4a files - the 4 examples in the tracks screenshot above are all m4a files with embedded images and id3 data, do you support that file type?

**Comment by marcelveldt** [comment]
can you contact me on discord? It would be really great to receive a collection of music files that are now not working so I can better test. I only have flac files with all tags present. I tried to "corrupt" some files by deleting tags but that still doesn't catch all usecases I guess.

**Comment by vk2him** [comment]
I've never used discord - let me work out how to do that - I can share some files to help

**Comment by marcelveldt** [comment]
With 1.0.16 (just published) this should be improved. Note that it is still important to properly tag your files
