### ISSUE TITLE
radio browser: crashes when browsing lists with several thousand radio stations

### ISSUE THREAD

**Issue by da-anda** [music-assistant/hass-music-assistant#1425]
### What version of Music Assistant has the issue?

2.0.0b62

### The problem

When browsing the stations by country and selecting a country with thousands of stations (like Germany or America), the provider seems to crash and cause a reload of the MA frontend. I could not find anything in the logs, Websocket connection seems to crash though, which leads to the reload of the frontend I suppose.

### How to reproduce

enable the radio provider, browse radio stations by country and select America or Germany

### What version of Home Assistant Core are your running

2023.07.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
First of all I didn't knew that a country could have several thousands of radio stations...
The issue does not exist when accessing the MA frontend directly. It's a limit in the ingress implementation of HA actually where we reach a certain threshold of the data size due to the huge listing from the Radio browser items for Germany.

**Comment by OzGav** [comment]
Will it just be a limitation then and not fixable?

**Comment by marcelveldt** [comment]
Oh no, I will fix it by implementing a paged load of the items

**Comment by OzGav** [comment]
@da-anda Fixed in b69. Thanks for the report!
