### ISSUE TITLE
Wrong port in readme and collision with Jellyfin NAS

### ISSUE THREAD

**Issue by fsaris** [music-assistant/hass-music-assistant#1458]
### What version of Music Assistant has the issue?

2.0.0b59

### The problem

The readme states port `8095` is used by default and wen occupied it will try the next port.

> The webinterface of the server can be reached on the tcp port 8095 by default (unless that port is occupied, then it picks the next available port). See the server's logging to confirm the port.

But this is (for the beta at least) not correct, it uses `8096` as default.

Should the readme be up-dated? Or is this only for the BETA version?

Would be great if the could be made configurable because now when restarting my host (so all containers) it starts earlier then the JellyFin container and claims port `8096` that JellyFin also wants to use.

If I would start the music assistant container after JellyFin is up it will indeed switch to a new port.

### How to reproduce

1. Install Jellyfin NAS (https://github.com/alexbelgium/hassio-addons)
2. Install Music Assistant (beta)
3. restart your host

JellyFin wil complain about not being able to claim the port `8096`

### What version of Home Assistant Core are your running

2023.7.2

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
The UI is on port 8095 and the stream server is on port 8096. Whether MA should change to accomodate Jellyfin or vice versa will have to be discussed.

**Comment by fsaris** [comment]
> Whether MA should change to accomodate Jellyfin or vice versa will have to be discussed.

Jellyfin uses the port already for a long time 😉 https://jellyfin.org/docs/general/networking/
But I get that you don't want to just change the port, that's why I proposed a option to make it configurable

**Comment by OzGav** [comment]
Actually you can already do that. SETTINGS>>CORE>>STREAMSERVER

**Comment by fsaris** [comment]
Where can I find these settings?

The addon shows only debug level

![Screenshot_2023-08-08-15-51-17-56_c3a231c25ed346e59462e84656a70e50](https://github.com/music-assistant/hass-music-assistant/assets/4019341/f647e1da-3ed4-47c7-b0fd-76e1d6965ceb)

**Comment by gieljnssns** [comment]
<img width="795" alt="Scherm­afbeelding 2023-08-08 om 18 06 30" src="https://github.com/music-assistant/hass-music-assistant/assets/17234951/5a3020b9-6ac7-423f-85c5-7f675a7d22e1">
<img width="797" alt="Scherm­afbeelding 2023-08-08 om 18 06 39" src="https://github.com/music-assistant/hass-music-assistant/assets/17234951/f9793083-7328-4459-9f41-ded39d8da21e">
<img width="806" alt="Scherm­afbeelding 2023-08-08 om 18 06 48" src="https://github.com/music-assistant/hass-music-assistant/assets/17234951/f8ba5445-f866-4430-9ef9-ab3fc63a97ff">
<img width="805" alt="Scherm­afbeelding 2023-08-08 om 18 06 56" src="https://github.com/music-assistant/hass-music-assistant/assets/17234951/50504375-4a44-44ff-b4c5-48f7737deb9a">

**Comment by fightforlife** [comment]
Important info regarding these screenshots:
This menu will only be shown if the streaming server is successfully started (Port 8096 is available)
If the streaming server is not starting because 8096 is already in use, it is not possible to change the port via WebUI.
Maybe a environment variable would be good.

**Comment by OzGav** [comment]
I understand that if MA cannot bind to the usual port it will try the next. So try subsequent port numbers

**Comment by instantepiphany** [comment]
Having it configurable would be ideal. There is already a config structure within the code, maybe it would be feasible to write this to disk and allow the user to modify it. 

Otherwise, if anything uses 8095, the user has to connect to the port (figuring out by checking the logs), change the setting and restart.

**Comment by OzGav** [comment]
The STREAMSERVER port is already configurable

**Comment by instantepiphany** [comment]
The configuration options don't work reliably for me - the UI lets you "change" but then shows the wrong values. 
My UI often shows they are both set to 8096, when really the web server is on 8095, and the streaming server is on 8096.

Setting them from an environment variable is common because it solves many use cases.

When I set MA up, I allowed a port for it in the firewall, but couldn't configure it until I started it on the default port, which was already taken. Would have been much easier if I could have configured it via environment variables, as I can link those to the port allowed in the firewall, making it more reliable and secure.

Trying subsequent port numbers isn't acceptable (on its own) because it means servers race to find a port, and they have different ports depending on that race condition, meaning you can't automate HTTP calls etc.

**Comment by misleadingrhino** [comment]
I'm also having this issue. The web interface starts on 8095 but the streaming server fails to start on 8096 because it's in use and then the Core Settings don't load, along with anything else. I just get "Invalid command: players/*" in the logs whenever I load a page.

**Comment by TimPasquini** [comment]
In the container's data folder, there is a settings.json where once you get it running there is a section:
```
"core": {
    "streams": {
      "values": {
        "bind_port": 8096
      },
      "domain": "streams",
      "last_error": null
    }
  }
```
Pre-populating this file and having some of the basic settings you might want to alter before first launch could be a functional alternative to changing any underlying code. Changing the 8096 value here should be persistent across all docker instances and allow you to launch the app without needing to shut down other services.
