### ISSUE TITLE
v1.0.17: 'Stream error on track' loggings

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#148]
Hi

I see these errors in my log which don't seem to impact playback (casting to a CC group continues fine):

```
Logger: music_assistant.mass.stream
Source: /usr/local/lib/python3.9/site-packages/music_assistant/controllers/stream.py:501
First occurred: 10:21:48 (21 occurrences)
Last logged: 10:47:13

Stream error on track 2a2dcc16-8baf-4b3a-ae99-c9373fee95db
Stream error on track 0736e58c-c6c9-4795-8571-347ebd6573d7
Stream error on track 07c36d42-93fc-44fb-88ad-bbdacd2716d2
Stream error on track 070b33e5-af22-456e-92da-18ae117a88ea
Stream error on track 9b3b0b5e-ed5e-4063-a6c7-1b405ad97ad9
```

**Comment by marcelveldt** [comment]
That is correct. It means the queue streamer skipped a track it was not available or network hiccup etc.
Reminder to myself: Make this error a bit more friendly and hide it to debug

**Comment by marcelveldt** [comment]
Have a look at your spotify playlist you was playing, good chance there are some tracks in there not available.

**Comment by marcelveldt** [comment]
This error happens if the queue streamer was not able to fetch the audio stream in time or did not get a response in time from the music provider. As this is all realtime (PCM) audio streaming this might happen if there's a small hiccup etc. I did not implement any retries yet so that can be improved. At the moment it just skips over the track and picks the next one.

So this error can happen if the track is not available due to network issue or its not available on the provider at all.

The ID is indeed an internal ID. The error is now logged just for me as indication how often this happens.
You're saying it happened 142 times in 60 tracks so that feels a bit too much. 

When I'm going to implement the seeking I need to make adjustments to this part of the code (the actual chunk retrieval of provider) and I will make this more robust. I assume you did not notice any audio hiccups ?

**Comment by erkr** [comment]
No the music plays fine, and according the 4+ hours playing, no noticeable amount of tracks where skipped (playlist is 4.40h in total)

**Comment by erkr** [comment]
Hi

I just verified these two tracks that where mentioned in de detailed HA log :
```
sox FAIL formats: can't open input file `spotify://track/4WE6YQ6kyf4VWUjrb5cBs0': No such file or directory
2022-05-12 14:48:01 ERROR (MainThread) [music_assistant.mass.stream] Stream error on track ca6667fa-bd7b-406c-9122-644d48864c49
sox FAIL formats: can't open input file `spotify://track/4ssBaxCHGQHRhzJmqNa2Yw': No such file or directory
2022-05-12 14:50:53 ERROR (MainThread) [music_assistant.mass.stream] Stream error on track 9b66bd52-99fb-4556-9717-43eb908438f3
```
Looked them up as these URLs in my browser
```
https://open.spotify.com/track/4WE6YQ6kyf4VWUjrb5cBs0
https://open.spotify.com/track/4ssBaxCHGQHRhzJmqNa2Yw
```
They both exist and play. So the errors are not related to missing tracks as such, but a failure to look them up. This doesn't seem to effect playback (no interruptions today, casting to the CC group).
These loggings quickly count up by the way (over 3000 in the last 8 hours).

**Comment by erkr** [comment]
Hi Marcel

Today I'm running the same playlist using the next version 1.0.18. In this version I didn't see these errors yet. 
Yesterday I was van to a group, now to one CC device. 
Something that you changed or continue testing with a group?

Eric

**Comment by marcelveldt** [comment]
So I dived into the code a bit more which logs this error and this happens if the decoder receives an empty chunk of audio, either due to a network error (packet loss) or it simply was slow in filling the buffer.

Is your network plagued by some network hiccups or nothing at all? Do you have a fast internet connection?
Anyways I will adjust this message to debug loglevel because it isn't exactly an error but more a notification but I still like to know why it happens so often on your setup. I can see the warning being logged too on my family setup (which is playing music all day long) but just a couple of times a day which is perfectly fine.

**Comment by marcelveldt** [comment]
As for the second issue with the wrong track inserted in the queue. That one is resolved in 1.1

**Comment by erkr** [comment]
> Is your network plagued by some network hiccups or nothing at all? Do you have a fast internet connection?

I guess not, one CC even has a wired connection using an USB to ethernet device, the other CC's are really near an AP to ensure good connections. Casting normally doesn't give any hiccups. My internet connection is also fast (500mb fiber)

> Anyways I will adjust this message to debug loglevel because it isn't exactly an error but more a notification but I still like to know why it happens so often on your setup. 
I'm currently running log settings at warning level. So I can do a test run today with debug level for MA 👍 . I will give you the logfile via discord then (to much tokes/keys inside :-)

Best Eric

**Comment by erkr** [comment]
Debug logging is enabled and I will cast for a while

**Comment by marcelveldt** [comment]
OK, just have a look please if the error is still logged very often. It is very normal that it is logged once in a while and the code can handle that just fine. Be warned that music_assistant logs pretty fanatic at debug level :-)

**Comment by erkr** [comment]
I know, so I only configured your part and debug level:
```
logger:
  default: warning
  logs:
    custom_components.mass: debug
    music_assistant: debug
```
 Attached the logging of 45 minutes casting music to my CC group. It really runs fine. I didn't notice any relevant errors 👍 
[home-assistant (2).log](https://github.com/music-assistant/hass-music-assistant/files/8695012/home-assistant.2.log)
 
This issue seems fully solved as well :-)

**Comment by marcelveldt** [comment]
Looks fine indeed. Thanks for your help testing!
