### ISSUE TITLE
Cannot install integration - user input malformed

### ISSUE THREAD

**Issue by freekeys** [music-assistant/hass-music-assistant#1799]
### What version of Music Assistant has the issue?

2024.1.0b2

### The problem

I have a fresh install of the add-on with the latest beta. I’ve added the integration fresh in HACS. When I try to install the  I get the error “User input malformed: expected str for dictionary value @ data['openai_agent_id']”

### How to reproduce

- install latest integration on HACS
- Install latest beta version of add-on
- Restart HA
- Start the add-on and configure 
- Add integration
- Choose conversation agent - none
- Untick expose players to assist
- Untick or tick “use official add-on”

### Relevant log output

User input malformed: expected str for dictionary value @ data['openai_agent_id']

### What version of Home Assistant Core are your running

2024.1.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by freekeys** [comment]
My mistake, I was on the beta

**Comment by rukai** [comment]
as per https://github.com/music-assistant/hass-music-assistant?tab=readme-ov-file#attention-running-home-assistant-20233-or-later since I am running the latest home assistant then I need to use the music assistant beta.
So I am also using `2024.1.0b2` and therefore hit the same issue:
![image](https://github.com/music-assistant/hass-music-assistant/assets/5120858/c7a06951-a615-407b-b4ac-dc67334ee8a7)

I'm not sure why this issue was closed?
Surely bugs in the beta still need to be fixed?
Or is there a later beta version I'm supposed to be using?

**Comment by OzGav** [comment]
You are confusing the integration and the addon. Install the latest version of the integration and the latest BETA of the addon.
