### ISSUE TITLE
Universal Player Group: Deleted Group, but now the non extisting player is always shown in bottom line

### ISSUE THREAD

**Issue by AlterDepp** [music-assistant/hass-music-assistant#1833]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

A deleted _Universal Group Player_ is still and always shown on the bottom line (two times). So it is not possible to stop other players or list their play list.

### How to reproduce

I have two  players (Squeezelite, integrated with _Slimproto_) which have been working correct in MA. Then I created a _Universal Group Player_ and added the two players. I tried to play some music, but the quality was really bad. So I turned one player off. Now I had problems with the _Slimproto_ players, so I deleted the _Universal Group Player_. Since then, I can only play music on one player, but not on the other. And now on the bottom line, there is always shown the _non existent_ group player (in two positions), regardless, if I play music with the working player or the other one.
When I click on the player-symbol, the player list opens on the right and the two players are shown, but the status is _playing (all players)_, where _all players_ is the name of the deleted group player.

### Relevant log output

No related log messages

### Additional information

Running on Home Assistant Yellow

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Screenshots would be useful to explain what is occurring and logs are required

**Comment by AlterDepp** [comment]
On the first screenshot, I selected a local mp3 file to be played on the first player (schlazi). which actually plays the track. But on the bottom line, I can only select the playlist for the non existent player _Alle Player_  (named _all players_ above). Also I can not stop the player or tune volume. Than I clicked on the playlist icon and the played track is not shown, but some other radio stream, which I may be played on the _Alle Player_ player:
![MA1](https://github.com/music-assistant/hass-music-assistant/assets/1706806/3390a28b-e38e-4379-b87b-08ebb25f5a93)

On the second screenshot I clicked on the right _Alle Player_  icon, to show the players. You see, the _schlazi_ player, which is actually playing, is shown as _untätig_ (which means _idle_ in english) and the non existent player is shown in braces.
![MA2](https://github.com/music-assistant/hass-music-assistant/assets/1706806/8b5939cc-3db4-4554-bea2-4ad71d7e1358)

An I found the MA logfile:
[d5369777_music_assistant_beta_2024-01-27T14-09-26.834Z.log](https://github.com/music-assistant/hass-music-assistant/files/14072596/d5369777_music_assistant_beta_2024-01-27T14-09-26.834Z.log)

**Comment by OzGav** [comment]
Grouping is being looked at. Thanks for your patience

**Comment by OzGav** [comment]
Fault finding comment. It appears to me that although the chain icon is showing the players as unlinked they remain grouped. This is evidenced by the (name) and also I observe a common queue on my instance.

**Comment by OzGav** [comment]
Please try again with beta88

**Comment by Mustreg** [comment]
I wonder if my issue is related to the same root cause:

1. No players are visible under the "Players" tab in MASS (Current version: 2.0.0b90)
2. Unable to add players to Universal Group Player/Sonos groups as players are not available for selection.
3. Howerver, the players are visible on the "blue" icon selection list and under the devices list in HA.
4. I **can** play music from Tidal to those individual players in MASS without any problems
5. I have tried to reinstall/restart/reconfigure MASS many times to no avail .
![image](https://github.com/music-assistant/hass-music-assistant/assets/105296988/4e3a8c80-0d9d-4fc0-b2f5-d97466524ec1)
![image](https://github.com/music-assistant/hass-music-assistant/assets/105296988/718d7c4b-044b-4090-9d07-895d7d95c343)
![image](https://github.com/music-assistant/hass-music-assistant/assets/105296988/9fe6852e-2f45-4ab8-80d6-1491acc39bf9)
![image](https://github.com/music-assistant/hass-music-assistant/assets/105296988/ec42588e-22d7-45d2-91c1-f58e5deebcc3)

**Comment by AlterDepp** [comment]
I tried with beta90. The strange behavior has gone.
But now I still can't play any music. I deleted the player and created a new one, but doesn’t help . The play button has no effect, the player stays _inactive_. My other player plays all music as desired, although both are squeezilite players. I do not know, if this is related to the other problem.
