### ISSUE TITLE
Stream title doesnt get resolved in certain online radio streams

### ISSUE THREAD

**Issue by ElektronikCZ** [music-assistant/hass-music-assistant#1878]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

Certain online radios dont display radio stream track info/title. A standalone player on my PC (Media player classic) does show the info however.

Example of a radio stream that does this:
https://stream.rcs.revma.com/3d47nqvb938uv
http://icecast2.play.cz/radiobeat128.mp3

Most other Czech radios have this issue. They seem to use icecast for the stream.

### How to reproduce

Add http://icecast2.play.cz/radiobeat128.mp3 or find Czech Radio BEAT in the browser and hit play.

### What version of Home Assistant Core are your running

2024.1.6

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Yeah OK i can see the info in VLC as well. This will get looked at in due course

**Comment by OzGav** [comment]
Related request is here https://github.com/orgs/music-assistant/discussions/1935#discussioncomment-8577226

**Comment by marcelveldt** [comment]
These appear to be HLS based radio stations (more and more radio stations use that nowadays). Although it provides better quality, its no longer based on ICY metadata so that is not provided anymore. There is an alternative metadata standard that works with HLS embedded in the substream playlists but it seems that most radio stations do not use that yet.

I don't know why it still works with media player classic, maybe that still gets the old ICY based stream.
If I check the urls you provided above, they all redirect to HLS

**Comment by marcelveldt** [comment]
So I checked these radio stations in detail and I can guarantee with 100% certainty that they stopped providing ICY metadata in the stream. They announce support but the metadata itself is just empty.

The only thing they provide is the radio station name but no track metadata, sorry.

VLC is btw also only showing the station name and not the track title;

<img width="640" alt="Scherm­afbeelding 2024-04-05 om 09 32 26" src="https://github.com/music-assistant/hass-music-assistant/assets/6389780/f780a422-d430-446b-9883-8de3f431324b">
