### ISSUE TITLE
Proactively scan on disc items to normalise audio

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1961]
### Discussed in https://github.com/orgs/music-assistant/discussions/1724

<div type='discussions-op-text'>

<sup>Originally posted by **expattaxtools** December 28, 2023</sup>
Is it feasible to normalize the volume levels between Dolby Atmos (eac3) and stereo (flac) encoded tracks? Currently, the Atmos tracks are noticeably quieter than the stereo counterparts. Additionally, is it possible to set a default preference for playback when a track is available in both Dolby Atmos and stereo formats?</div>

[marcelveldt](https://github.com/marcelveldt)
[4 days ago](https://github.com/orgs/music-assistant/discussions/1724#discussioncomment-8564858)
Maintainer
This is where the volume normalization feature is invented for. Only problem is that we do not pre-fetch that info. Its only measured after first playback. I guess we can add an option to proactively scan the items that are on disk

**Comment by OzGav** [comment]
Please check if this has been fixed in beta 109

**Comment by OzGav** [comment]
@expattaxtools please check if the latest beta has fixed your problem

**Comment by expattaxtools** [comment]
Unfortunately not. There is still a huge difference in volume levels between the atmos (m4a) and flac version of the tracks that requires volume adjustments. For example the atmos version on volume 40 sounds about the same as the flac on volume 20. If you need me to I can send you the same track in the two different formats to see what I mean. I have the volume normalization enabled. Not sure if there is any other specific setting I need to turn on.

**Comment by marcelveldt** [comment]
Why are you trying to play Dolby Atmos using Music Assistant ? We wont be able to process that anyway, we only do stereo. 
I assume those Atmos tracks are multi channel ? Supporting Atmos (or multi channel in general) would be a feature request.
So far there has not been any interest in that (you're the first) and we do not even support any targets that support it.

**Comment by expattaxtools** [comment]
My concern doesn't involve configuring Music Assistant to play in surround sound. The problem arises when I have albums available only in Atmos format. When I create playlists or enable shuffle mode, the noticeable difference in volume levels becomes quite bothersome.

If achieving volume leveling between the Atmos and FLAC versions is not feasible, another solution could be prioritizing the format. For instance, when both Atmos and stereo versions of the same track are available, Music Assistant could opt for the FLAC stereo version instead of the Atmos. This approach would effectively resolve the issue, as currently, the player tends to select the Atmos version more frequently.

**Comment by OzGav** [comment]
Not sure how you have your folders setup but moving the ATMOS tracks out of the path that is scanned by MA might be a solution

**Comment by expattaxtools** [comment]
Thank you for your suggestion. I see that more of a workaround than a definitive solution to the issue. In my primary room, I have a music player platform for surround sound playback, making updating everything a daunting task. In my office and bedrooms, I use a stereo setup with a music assistant. Organizing tracks into different folders isn't ideal, especially for albums with mixed formats like Atmos and stereo. Fortunately, the music assistant effectively stacks similar tracks, regardless of format. Introducing a priority setting could offer a quick fix. For instance, users could select which version of a track to play based on the player's capabilities (mp3, flax, m4a atmos). While it still requires multiple versions of the same track, it's a manageable solution. Ideally, being able to adjust volume levels automatically for Atmos tracks, considering their quieter mastering, would be the optimal solution

**Comment by OzGav** [comment]
As Marcel said above if the ATMOS tracks are multichannel then they can't be processed.

**Comment by expattaxtools** [comment]
I understand, so if we can’t make the multi channel audio louder, can we make the stereo quieter? :)

**Comment by OzGav** [comment]
As a guess you could play with turning on and off the normalisation and changing the value?? Its a per player setting

**Comment by OzGav** [comment]
We are closing this as Marcel's intent has been implemented and we can't help with multi-channel audio at this time. As suggested you can open a feature request in the discussions area and see how many others want this.

**Comment by expattaxtools** [comment]
Ok. I have tried the normalization but it applies the gain adjustment to all tracks, even the ATMOS ones. 
Is there a way to get the full file name or the stream details of the currently playing tracks?

**Comment by OzGav** [comment]
There are a lot of attributes that you can see in the dev tools of HA if you select the MA player entity

**Comment by OzGav** [comment]
Yeah I am not sure what you are trying to do but that is all the information currently sent to HA

**Comment by expattaxtools** [comment]
I was planning to create an automation to adjust the volume levels based on the stream details or the file extension. :)

**Comment by OzGav** [comment]
Yeah unfortunately one of the main features of MA is make different versions of a release transparent so those details are not sent.

**Comment by expattaxtools** [comment]
Unfortunately... Thank you for looking into this for me. It would be a great feature then to be able to select which version of the release to play.

**Comment by OzGav** [comment]
That is opposite to the current philosophy. MA links and collapses the same releases together in the DB and selects the highest quality version to play. Looking back at an earlier suggestion of yours, MA always streams at high quality (except in a couple of cases where an option is provided) as the intent of the project is to provide the highest quality stereo music experience possible . So providing options to select different quality version is not something that I think Marcel will want to put time into providing especially since you are one of ten thousand users. Again I can only suggest trying to come up with a cunning way of making the ATMOS tracks not visible to MA.

**Comment by expattaxtools** [comment]
I understand. Thank you again.

**Comment by marcelveldt** [comment]
Is there a specific reason you choose tracks encoded with Atmos ? Are these multi channel ?

To what kind of device are you sending the audio to because I am not aware of any devices we support in MA that supports multi channel out of the box, so its basically a waste of resources (and sound quality!) to even send these multi channel Atmos tracks.

Let's put a feature request on the backlog to investigate what is needed for multi channel audio.
If there is enough interest we can look into that in a later release. I believe Roon has some support for it as well.

For now I'd like to know which players and your reasoning behind it so I can better understand.
Also, maybe you can send me one of those files so I can have a look what ffmpeg is doing with it ?

**Comment by expattaxtools** [comment]
Yes, these tracks are multi-channel. 

In my living room, I have a surround sound setup with a receiver that allows me to play them back in surround sound using a different player. However, in my office and bedroom, I only have a stereo setup. The player I use in my living-room can bitstream the Atmos tracks and process the stereo ones, making it easy to adjust the volume to account for the difference, as the volume adjustment doesn't affect the Atmos tracks.

The music assistant does a good job of playing back both types of tracks in stereo, but the varying volume levels are quite bothersome since there's no way to adjust the volume separately for each type and the volume normalization does not help as they are mastered at different levels.

While having support for multi-channel playback isn't crucial since I have a receiver for that purpose, being able to adjust the volume based on the stream format would be highly beneficial. However, it appears challenging to implement this feature as Music Assistant doesn't provide access to the information about the currently playing track stream information or file name at this time.

Please let me know how I can send you a track in both file formats so you can see how it is handled in ffmpeg and what the volume difference is like.

**Comment by marcelveldt** [comment]
You can send them to me on discord if you want in a PM (my username is marcelveldt)
Otherwise an email is also fine (m.vanderveldt[at]outlook.com)
