### ISSUE TITLE
Getting an error message after restarting HASS Core

### ISSUE THREAD

**Issue by baj24** [music-assistant/hass-music-assistant#242]
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 9:25:24 AM (1 occurrences)
Last logged: 9:25:24 AM

Setup failed for custom integration mass: Unable to import component: No module named 'aiofiles.ospath'

I haven't seen anyone else with this issue, unless I'm missing something.

**Comment by marcelveldt** [comment]
Probably this means you have another custom integration set-up that requires aiofiles and it installed an older version than the version required by MA (which is 0.8+)

**Comment by groenmarsmannetje** [comment]
I have the same issue

**Comment by marcelveldt** [comment]
There's another custom integration causing a conflict. Music Assistant requires aiofiles 0.8.x (the latest) for a few functions. 
I've just looked at the code and with a few adjustments I can make it compatible with aiofiles 0.7.x (previous version) so I'll go with that instead of trying to search for a needle in a haystack for the integration causing the conflict.

So long store short you may expect this issue to be fixed in next update.

**Comment by marcelveldt** [comment]
Fix released in 1.1.17
