### ISSUE TITLE
Timeouts when syncing Apple Music tracks

### ISSUE THREAD

**Issue by faelenor** [music-assistant/hass-music-assistant#2604]
### What version of Music Assistant has the issue?

2.1.0b14

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Apple Music track sync always fails with timeouts (the 5 retries are failing). There is a lot of "Skipping track. No catalog version found for ..." warnings in the logs before it happens. Most of these warnings (possibly all?) are from CDs that were imported a long time ago, so maybe the timeouts are related.

Artists and albums are correctly synced, but tracks and playlists are empty. BTW, shouldn't you do the playlist sync even if the tracks sync failed?

### How to reproduce

Sync Apple Music provider.

### Music Providers

Apple Music
RadioBrowser
Music Assistant

### Player Providers

AirPlay

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16149292/music-assistant.log)

### What version of Home Assistant Core are your running

2024.6.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by MarvinSchenkel** [comment]
Thanks a lot for this extensive log. I will try and see if I can figure out why some of your requests are timing out. The timeouts are probably not related to missing catalog items, since all those numbers you are seeing are catalog id's. Do you have any other type of music in your library, e.g. purchased music?

The reason you do not have playlists is because the sync stops because of an error in the tracks (playlist sync happens after tracks). I see your point about just continuing the sync, but we'd rather just fix the errors and make sure we can sync everything, or at least gracefully log what cannot be synced.

**Comment by faelenor** [comment]
Afaik, we don't have any purchased music.

**Comment by OzGav** [comment]
@faelenor please check with 2.1.0rc1

**Comment by faelenor** [comment]
It still fails, but the error is different this time. I forgot to set the log level to debug, tell me if you need another log file.

[logs.txt](https://github.com/user-attachments/files/16216646/logs.txt)

**Comment by OzGav** [comment]
@MarvinSchenkel

**Comment by MarvinSchenkel** [comment]
This is a different error totally unrelated to Apple Music, will be solved anyway. Good news if you're not seeing any timeouts though!

**Comment by xmirakulix** [comment]
Found it in my installation as well, see PR https://github.com/music-assistant/server/pull/1499

**Comment by faelenor** [comment]
It works now, thank you!
