### ISSUE TITLE
Tracks doesn't show number of tracks until...

### ISSUE THREAD

**Issue by Symbiot78** [music-assistant/hass-music-assistant#273]
A few seconds has passed.

also .. within those few seconds I cannot click the 'tracks'.. it's greyed out.

Then number of tracks appear and I can click it.

**Comment by marcelveldt** [comment]
As discussed on discord it's like this by design:
When you open the Music Assistant panel, it starts fetching the media items upfront to the browser cache.
One a library category is preloaded, it will activate the button and show the total count.

I can change this and show the count already before prefetching items.

**Comment by erkr** [comment]
Nicely fixed in Beta 7, thx
