### ISSUE TITLE
Add dedicated shuffle and repeat button (shuffle/repeat playlists)

### ISSUE THREAD

**Issue by dpomnean** [music-assistant/hass-music-assistant#274]
Add the option to shuffle/repeat

**Comment by marcelveldt** [comment]
Shuffle and repeat are there already.
Click the queue button to show the queue items. Click the menu top right.

<img width="1174" alt="Schermafbeelding 2022-06-01 om 08 20 14" src="https://user-images.githubusercontent.com/6389780/171340337-ee909c2b-2060-4e89-8eba-161969346c6e.png">

**Comment by marcelveldt** [comment]
Reminder to myself: add dedicated shuffle and repeat button in the OSD of the Music Assistant panel (not in mobile view)

**Comment by erkr** [comment]
I would like to add pause/resume in case other apps are casting. Now I only see the stop button.

**Comment by marcelveldt** [comment]
> @marcelveldt I would like to add pause/resume in case other apps are casting. Now I only see the stop button. Now MA becomes mature, these details start to matter

pause/unpause is possible, resume would be a UX problem. You press the play button from the MA application and it starts playing something else not from MA. I understand the usecase, that's why I implemented it for the "mass" entities in HA itself and the announce feature. From the MA frontend panel where MA is supposed to be the media controller it is very confusing or I must come up with a smart signal or something but that is kinda low prio

**Comment by erkr** [comment]
Pause / unpause is fine 😎
Maybe I'm not using the right wording. Unpause and resume are kind of the same for me
