### ISSUE TITLE
python bug

### ISSUE THREAD

**Issue by SandaleZ** [music-assistant/hass-music-assistant#3011]
### What version of Music Assistant has the issue?

2.2.7

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Errors shown in logs

### How to reproduce

Comes up daily

### Music Providers

Radio HA, Apple Music

### Player Providers

Sonos

### Full log output

`2024-10-07 08:16:09.308 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py", line 1336, in _enqueue_next
    next_item = await self.preload_next_item(queue.queue_id, current_index)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py", line 1113, in preload_next_item
    queue_item.streamdetails = await get_stream_details(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/helpers/audio.py", line 195, in get_stream_details
    LOGGER.debug("Getting streamdetails for %s", queue_item.uri)
                                                 ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'uri' `

### What version of Home Assistant Core are your running

2024.10.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
With the volume of requests for assistance on here, Discord and the HA forums we need people to provide the information requested in a concise manner. You are getting this standard response because you have not supplied the information requested in the troubleshooting docs or in the issue report template and we are unable to quickly pinpoint the problem. Please review and supply the requested information for a more timely response to your problem. Thanks for your understanding.
