### ISSUE TITLE
The "Don't stop the music" toggle does nothing.

### ISSUE THREAD

**Issue by riddley** [music-assistant/hass-music-assistant#3064]
### What version of Music Assistant has the issue?

2.0.3b33

### What version of the Home Assistant Integration have you got installed?

20204.10.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Unwanted music is added to the playlist when the currently selected music ends.

### How to reproduce

Play a single track manually and music will continue to play after that song is over despite the "Don't stop the music" toggle being off.

### Music Providers

Tidal has the problem.

### Player Providers

I'm using snapcast to a Pi.

### What version of Home Assistant Core are your running

2024.10.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
With the volume of requests for assistance on here, Discord and the HA forums we need people to provide the information requested in a concise manner. You are getting this standard response because you have not supplied the information requested in the troubleshooting docs or in the issue report template and we are unable to quickly pinpoint the problem. Please review and supply the requested information for a more timely response to your problem. Thanks for your understanding.

**Comment by marcelveldt** [comment]
The don't stop the music toggle has been removed from the queue settings.
You can now set it per (player)queue) if you like, its an option in the contextmenu for the player (within the player sidebar or the full screen player).
