### ISSUE TITLE
Sirius XM - Can't update credentials after entering a bad password

### ISSUE THREAD

**Issue by smartypants1138** [music-assistant/hass-music-assistant#3127]
### What version of Music Assistant has the issue?

2.3.2

### What version of the Home Assistant Integration have you got installed?

2024.11.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I attempted to add the Sirius XM integration, unfortunately, I provided the wrong password. But, I don't see the integration in MA. When I attempt to Add SXM again, I see this message; Provider siriusxm already loaded and only one instance allowed

### How to reproduce

I attempted to add the Sirius XM integration, unfortunately, I provided the wrong password. But, I don't see the integration in MA. When I attempt to Add SXM again, I see this message: "Provider siriusxm already loaded and only one instance allowed"

### Music Providers

SiriusXM

### Player Providers

N/A

[MA Log File.txt](https://github.com/user-attachments/files/17623280/MA.Log.File.txt)

**Comment by OzGav** [comment]
Pleas edit your post and remove the pasted log entry and attach it as a file.

**Comment by smartypants1138** [comment]
Done, the Download logfile link doesn't provide a way to save the file as specific time, so I saved everything as a txt file.

**Comment by OzGav** [comment]
@btoconnor

**Comment by OzGav** [comment]
Spotify has a CLEAR AUTHENTICATION button so you can start again

**Comment by btoconnor** [comment]
I'll play around with the integration this weekend by putting in some bad credentials, but my understanding was that the integration isn't even showing up right now to edit?

**Comment by smartypants1138** [comment]
That's correct, the configuration isn't showing up to edit.

Sent via the Samsung Galaxy S22 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by OzGav** [comment]
@btoconnor getting a few more reports about this…

**Comment by btoconnor** [comment]
It's not clear to me what the fix here is, or if this should be handled in the SiriusXM player provider or the MA core.

If someone adds bad credentials, and then the player disappears from MA, this sounds to me like an issue with the MA core.  I can recreate that adding bad credentials to the MA and it fails in a spinning loop to add it.  The code is currently correctly raising `LoginFailed` when bad credentials are added, and I don't see any other providers handling that exception.

There's no button that I can provide on the settings page that will clear authentication, because the integration isn't showing up.  If there's a different error besides [`LoginFailed`](https://github.com/music-assistant/server/blob/dev/music_assistant/providers/siriusxm/__init__.py#L139-L140)) that I can throw to make it so that this is editable, I'm happy to adjust it.

I would expect if an Exception is raised during the call to `handle_async_init(...)`, that MA would handle this and not register the music player as registered, which is the issue here AFAICT.

**Comment by OzGav** [comment]
@marcelveldt ?

**Comment by btoconnor** [comment]
I pushed up a patch to try and workaround an issue with the `sxm-client` with https://github.com/music-assistant/server/commit/4744d18d7325097d9ef51a7955f987b4fed042f2

I still think there's an underlying issue here that MA should handle exceptions thrown in `handle_async_init(...)` and not treat that provider as registered though.

**Comment by OzGav** [comment]
@smartypants1138 please confirm this is fixed in 2.3.3 / 2.4.0b5

**Comment by murfnturf1** [comment]
In case the OP does not reply, I was having the same issue. The fix worked for me. Was able to re-enter my credentials correctly and it set itself up as it should. Thanks for pushing the patch!
