### ISSUE TITLE
Can't connect Yandex Station 

### ISSUE THREAD

**Issue by igoriosdeveloper** [music-assistant/hass-music-assistant#3193]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.11.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

MA can't find Yandex station 

### How to reproduce

there is no some specific terms to reproduce situation

### Music Providers

all of them

### Player Providers

all of them

### What version of Home Assistant Core are your running

2024.11.2

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
With the volume of requests for assistance on here, Discord and the HA forums we need people to provide the information requested in a concise manner. You are getting this standard response because you have not supplied the information requested in the troubleshooting docs or in the issue report template and we are unable to quickly pinpoint the problem. Please review and supply the requested information for a more timely response to your problem. Thanks for your understanding.
