### ISSUE TITLE
Add support for Universal Media player

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#457]
The Universal media player is now working as a source for MA. But I noted some issues.
My universal media player wrapped a normal Chromecast,  where mainly power is redirected to a power plug.

The issues:
Minor: Name in MA is the entity_id , not the (friendly) name as defined in the template
Bug: after the first MA reload the mass player became unavailable, this was not fixed after a restart or unhide

![image](https://user-images.githubusercontent.com/4363599/174485664-5db9e9a1-6901-4829-8ab5-dc85f66bffc9.png)

**Comment by marcelveldt** [comment]
Using a Universal player as player in Music Assistant is not possible. In the beta version for MA 2022.8 I've even added it to the blacklist to prevent people from using it as it can cause serious side effects due to the "wrapped" nature of the universal player.

I am going to try to add support later but my first attempt to do so failed so it needs more thinking.
I may fix this for the final 2022.8 version of MA but it may also take me longer or never at all if I keep hitting too many roadblocks.

**Comment by sophof** [comment]
I will stop using it for now as suggested, but just to make the 'buglist' complete, for me the unavailable issue is also still there (the OP says it is fixed for him).

**Comment by OzGav** [comment]
@erkr do you know where this is at?

**Comment by erkr** [comment]
I close this issue as it was very specific for MAv1.
Marcel promised to have some options on using other HA entities for volume or power control in the new HA integration.
