### ISSUE TITLE
[planned feature] Global search function

### ISSUE THREAD

**Issue by marcelveldt** [music-assistant/hass-music-assistant#61]
The search view still needs to be implemented in the new panel

**Comment by rml1111** [comment]
A clarifying question on this feature request - is this for global search of the Spotify (or other source) library or a direct search on Spotify. It would be ideal if a direct search on Spotify to enable access to music not in library from Lovelace. The only way that I am aware of to search Spotify directly from Lovelace frontend Mopidy, which does not work directly with Chromecast destinations.

**Comment by marcelveldt** [comment]
This global search will search all music sources connected to Music Assistant, including Spotify

**Comment by loryanstrant** [comment]
I'd love this feature to be added, because I've had to go through the whole Mopidy setup and embed it via iFrame in my dashboard, but found the search function was too literal.
Where searching through the Spotify interface you get the most popular results (and therefore usually correct), but with Mopidy it's alphabetical. Unfortunately as a result this caused frustration for the user I need this to work most for - my wife.
Happy wife = less questions when more HA-related devices arrive. :-)

**Comment by marcelveldt** [comment]
haha that sounds too familiar. I've already prepped the entire backend for the global search so expect this to happen fast, in fact I'm missing the global search myself too.

**Comment by marcelveldt** [comment]
2022.7 has been released, including the global search feature!

**Comment by loryanstrant** [comment]
Awesome, updating and rebooting to give it a go now!
Thank you!!!
