### ISSUE TITLE
ID3 data sent to music_player out of sync with music_player.mass

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#640]
### What version of Music Assistant has the issue?

2022.7.0.b3

### The problem

Background - My denon amp has a display window that shows the ID3 data from the currently playing song. It seems to be sourcing this from the non mass music_player.

When music is being played though a device, the music_player entity for that device displays a scrolling list of songs in the current playlist. The music_player.mass will only display the currently playing song.

Since my denon displays the music_player "data", I would rather that the non mass player only display currently playing song rather that scrolling through all songs in queue so that my Denon displays the currently playing song. Refer screen shots

### How to reproduce

Note - in all screenshots the mass player is on top of the non mass player.

This is what was in the queue before playing started:

![Image 010](https://user-images.githubusercontent.com/22878629/178174050-e721af0c-9b8a-4af8-8e1f-463ffe461ddc.jpg)

When queue is initially started, mass and non mass players are in sync:

![Image 009](https://user-images.githubusercontent.com/22878629/178173989-13f4083a-d1d2-46d4-90a0-2f243cfb13fd.jpg)

Shortly after the non mass player displays the next song in queue while the first song is still being played

![Image 011](https://user-images.githubusercontent.com/22878629/178174178-f367fc2e-80d9-42d6-9f54-18423f6d1c14.jpg)

The next song is then displayed and so on ...

![Image 014](https://user-images.githubusercontent.com/22878629/178174596-a5a22ee7-374a-48a7-9d58-76f625a5713f.jpg)

### Relevant log output

No errors are displayed 

### Additional information

I'm unsure if this is "normal" behaviour for the music_player entity when it is playing a list?

### What version of Home Assistant Core are your running

2022.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
Can you please check if this is fixed in the 2022.7 beta 4 ?

**Comment by vk2him** [comment]
No beta 4 has same behaviour - Thanks

**Comment by marcelveldt** [comment]
I'm not sure if I can fix this... Your receiver seems to be caching ahead the audio data and instead of displaying the "icy" metadata of the currently playing track, its displaying whatever it has buffered. That's a serious design flaw for such a big brand.

The ICY metadata is encoded with the stream, the same way as online radio stations do this.
So we send one long stream of audio from MA. Every x bytes, there's a metadata chunk about the audio being sent.
The only difference is that online radio stations are live so you can't buffer ahead more than a few seconds tops while MA allows you to cache ahead whatever you need/ For example Sonos caches about 5 minutes ahead.

I can put a small guard in the code to prevent the player from buffering more than a full track ahead but that might harm other players performance so I need to think about this a bit more.

Maybe you better set the audio stream to FLAC instead ?
That will most probably disable the metadata but you get better audio quality in return.
You can change the audio stream to FLAC from the HA settings --> integrations --> Music Assistant --> devices --> pick the MA device for your receives --> See the config entity there where you can select the stream type.

**Comment by vk2him** [comment]
Marcel - note that the issue can be reproduced by yourself by looking at the non mass media_player as that displays the rolling list of tracks - it's not really anything to do with the denon as it is simply displaying the same information that the media_player entity displays. Thanks

**Comment by vk2him** [comment]
Now I'm super confused - lol - I can confirm that my non mass player displays the metadata - you can see it in the screenshots above - the all blue entities are the media_player for the denon - here's the yaml for it:

```
type: media-control
entity: media_player.avr_x4000_2
```

**Comment by vk2him** [comment]
Yes super confusing :) 
I've just changed the stream type to flac - I wasn't aware of that option as that setting was hidden by default so I had to enable it. I tried streaming to it again with flac selected and it still displays the metadata .... how do I know it's actually streaming flac or mp3 ? I tried changing while it was playing a track and the music wasn't interrupted.  Do I need to restart HA after enabling the stream type?

**Comment by marcelveldt** [comment]
Its kind of an advanced setting fr which I still need to create some frontend in the Music Assistant UI.
You need to restart the stream. So either stop and play or just press next track.

**Comment by marcelveldt** [comment]
OK, well that is good news and bad news at the same time :-)
It means you can benefit of the lossless audio quality AND still have metadata. Now to get the correct metadata haha....

Maybe I can create a small advanced setting for this:
- to control how much music (in seconds) may be buffered ahead.
- OR to control what metadata is embedded. Of the current playing track (as in what you hear) versus what audio frames are sent to the audio device.

I can also start with a somewhat pragmatic solution and just wait after each track is buffered and only allow like 10 seconds of buffer head

**Comment by vk2him** [comment]
fixed with beta 9 - thanks!!!
