### ISSUE TITLE
Error failing to get MB artist ID

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#654]
### What version of Music Assistant has the issue?

2022.7b4

### The problem

Still seeing this error occur.  https://github.com/music-assistant/hass-music-assistant/issues/565

Anthony Warlow does have a MB ID https://musicbrainz.org/artist/7ad0a863-e2e0-4038-be9b-02f4011ee348

### How to reproduce

It only occurs on select artists.

### Relevant log output

Logger: music_assistant.metadata
Source: /usr/local/lib/python3.10/site-packages/music_assistant/controllers/metadata/__init__.py:158 
First occurred: 3:24:23 PM (3 occurrences) 
Last logged: 4:01:21 PM

Unable to get musicbrainz ID for artist Anthony Warlow !
Unable to get musicbrainz ID for artist Genesis Lynea !
Unable to get musicbrainz ID for artist 12 Days !

### What version of Home Assistant Core are your running

2022.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
While being logged as error, it is pretty harmless. It just means it couldn't grab the musicbrainz id at that moment with the combination of track/album is was processing at that time. The log level is a bit harsh atm but it helps me diagnosing how many times it is off. There's a good chance that it grabbed the musicbrainz id a few seconds later for another track.

Maybe you have a song by such an artist that has some incorrect tags. It sends the artist + album Nad/or track name to musicbrainz to get an id back.

I'll adjust the logging a bit so that will log at info level instead of warning and include some more info like what info it used to try to get the match. Maybe that helps in better finding out if there's an error in the code or in the tags.

**Comment by OzGav** [comment]
Perfect sounds good

**Comment by marcelveldt** [comment]
This one is fixed a few betas back.
