### ISSUE TITLE
Failed to startup

### ISSUE THREAD

**Issue by lecrams** [music-assistant/hass-music-assistant#788]
### What version of Music Assistant has the issue?

latest

### The problem

Checking my integrations page I have the following error:
![image](https://user-images.githubusercontent.com/74721082/182386188-c7433f94-02f5-4cae-9ff2-f72daacc1d07.png)

There are no logs wrt MA. What can be wrong?

### How to reproduce

Just check the HA integration page

### Relevant log output

None available

### Additional information

None

### What version of Home Assistant Core are your running

2022.7.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by marcelveldt** [comment]
As the message literally says: 
You installed a version of Music Assistant that is not compatible with Home Assistant.
Either downgrade Music Assistant in HACS to the latest 2022.7.x stable release or wait for the release of Home Assistant 2022.8 tomorrow.

TIP: If you're not running the HA beta program, you should probably also disable HACS beta updates?

**Comment by Danieldiazi** [comment]
Same problem here. 
I just upgraded Music Assistant and then I get the same message.

**Comment by juhanjuku** [comment]
> 
@marcelveldt 
Can't find where to disable HACS beta updates?

**Comment by Firesphere** [comment]
> As the message literally says:
You installed a version of Music Assistant that is not compatible with Home Assistant.

I understand the message, I would, however, not expect this to happen after an update of either Music Assistant to version 2022.7.4 or Home Assistant to version 2022.7.7, as those are both the latest stable versions.

**Comment by marcelveldt** [comment]
@Firesphere this message will only appear if you install MA version 2022.8.x on HA version 2022.7.x
So it will NOT be there if you install MA 2022.7.4 on HA 2022.7.7

**Comment by Firesphere** [comment]
> @Firesphere this message will only appear if you install MA version 2022.8.x on HA version 2022.7.x So it will NOT be there if you install MA 2022.7.4 on HA 2022.7.7

I have MA 2022.7.4 on HA 2022.7.7 and got this message as well...

**Comment by OzGav** [comment]
Can you post a screenshot showing the installed MA version from within HACS?

**Comment by marcelveldt** [comment]
> I have MA 2022.7.4 on HA 2022.7.7 and got this message as well...

That is simply not possible, because the 2022.7.4 code does not even have this check yet. I added it only in the 2022.8.x version to prevent support issues like this. So I'm afraid something is wrong in your setup where the beta accidentally got installed ? Maybe just try to reinstall the 2022.7.4 version with HACS ?

**Comment by lecrams** [comment]
downgraded and everything is fine now. Thx for the support

**Comment by Firesphere** [comment]
> Maybe just try to reinstall the 2022.7.4 version with HACS ?

Installed version from HACS clearly said 2022.7.4. But a reinstall has resolved the issue.
I have absolutely no clue, if it had updated itself, or something else... I've never even enabled beta versions...

**Comment by fribse** [comment]
> > I have MA 2022.7.4 on HA 2022.7.7 and got this message as well...
> That is simply not possible, because the 2022.7.4 code does not even have this check yet.

Ha ha ha, well I saw it too, I reverted to 2022.7.3, and it worked again, so something is definetely going on.

**Comment by fredleger** [comment]
same here no betas enabled but smae message

**Comment by marcelveldt** [comment]
> I wonder if HACS by accident got the wrong version installed? I just tried updating to 2022.7.4 again, and now it does't give that weird message.

There has been a very short timeframe for like a few hours where the 2022.8.2 beta did not get marked as "prerelease" due to the simple fact I forgot that damn toggle. I changed the toggle afterwards but maybe HACS aggressively caches stuff and did not notice the new prerelease flag or something.

Imo there's a real missing feature in HACS namely to tie a release to a specific HA version.
Each HA version comes with various breaking changes, especially for a complex project like this so you really want to tie a version published on HACS to a minimum HA version to prevent a mess like this from happening...

**Comment by fribse** [comment]
Could very well be, but I'm pretty sure that it still said 2022.7.4? Oh well, all is well now 😁
