### ISSUE TITLE
Configurable base_url

### ISSUE THREAD

**Issue by xeor** [music-assistant/hass-music-assistant#802]
### What version of Music Assistant has the issue?

2022.8.0

### The problem

Devices are connecting to mass using an autogenerated url and a static port. This doesn't make much room for advanced setups where you have home-assistant running behind a reverse-proxy, inside kubernetes or similar, making it hard and even impossible on some setups to get mass running.

### How to reproduce

Try to setup mass where the autodetected url is not the one the cast devices can reach mass on.

### Additional information

I run home-assistant inside kubernetes behind a reverse proxy. I've exposed the mass endpoint using kubernetes ingress.
Changing https://github.com/music-assistant/music-assistant-lib/blob/b02a58d89ff448604127f8db2a6f1af7dc785aac/music_assistant/controllers/streams.py#L59 to `https://mass.mydomain.com` instead of the default `f"http://{self._ip}:{self._port}"` made my setup work.

A good way to handle advanced setups is therefor to make this field configurable..

### What version of Home Assistant Core are your running

2022.8.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
Why do you want to serve the audio stream on https and overcomplicate stuff like this ?
This base url is NOT for the api or web interface, its for the audio stream which needs to be **as simple as possible**, so avoid local dns names and avoid https. It works maybe in your setup but I can guarantee you that a lot of players will not like this.

For example google cast players have the google dns servers hardcoded and will never be able to resolve internal dns names. That is why the stream service is hosted on its own as-simple-as-possible http port, otherwise I could have proxied it on the HA webserver. I did that for a reason.

So, I'm not a big fan of making this configurable because it will cause more support to handle and it will most likely not work in a lot of situations. Maybe some sort of hidden environmental variable that nobody knows about ;-)

What's wrong with opening a tcp port in your LOCAL network ?
Let alone all dns issues, why add the overhead of https to the audio stream which is local only ?

**Comment by xeor** [comment]
Adding this extra mass.mydomain.com might seam complicated, but with the rest of the setup, this is really just a definition for me, more or less 2 lines, one with the domain, and one with destination, domain, https all taken care of by another layer :)

There are others that have such a setup as well, there is a whole community of "kubernetes at home" that loves to automate their infrastructure and services.
There are even more people that runs home-assistant behind a reverse-proxy, so they can get it on their own domain without the port.

There are multiple way for these people to expose the port, with or without https, local or public behind an authentication proxy and whitelisting of sources. The thing is that most, if not all of those setup will need some sort of configuration for the base_url, that could be changing the internal hostname, ip, port or something else.

The people with those kind of setups are probably reading about mass first tho, the docs or github README, so I agree, we don't need to expose it as a configuration-box.. I'm not sure if it should be completely without doc tho? :p Or?

I can submit a PR to get this in.. Something simple around environment an variable? `MASS_BASE_URL`? Docs?

**Comment by marcelveldt** [comment]
I have given a very detailed answer here:
https://github.com/music-assistant/hass-music-assistant/discussions/794#discussioncomment-3331209

This is not about running Home Assistant web interface behind reverse proxy etc. it has nothing to do with a web interface.
We are talking about the audio stream service here, yes that is http but that is all it is, the protocol. 

There are very good reasons to host that on HTTP only and avoid dns lookups.

I'm fine with an undocumented ENV variable to override the base URL if you are willing to take the risks of slower seek times, buffer issues, audio dropouts etc. I simply won't support it because after 3 years working on this project my conclusion is that playback just works most reliable if there's not https or dns lookup involved.

Undocumented because I'd rather tell experienced guys like you that the setting exists than having to support people who use this setting in the wrong way if you get what I mean. Or maybe document it and link to my rant linked above aboyt my choices to host this on a separate port ;-)

I hope you get what I mean. It's not that I do not want to support your setup but I just know it's going to cause trouble. Maybe not for you because you're in luck but it will for others.
