### ISSUE TITLE
Searches may return duplicates by accident

### ISSUE THREAD

**Issue by DutchJaFO** [music-assistant/hass-music-assistant#822]
### What version of Music Assistant has the issue?

2022.8.1

### The problem

After fixing a duplicate artist result I noticed that the artist search still would return results that contained duplicates as well as incorrect results.

### How to reproduce

Artist search : 'weird'

Initially return :
![image](https://user-images.githubusercontent.com/39138434/183300051-9de8efb4-5bce-43d3-ab6a-81046f3b4871.png)

doing a backspace and re-adding the last letter appears to give the expected results :
![image](https://user-images.githubusercontent.com/39138434/183300084-fe985e83-840e-49f7-aaa6-23edf7da18be.png)

The results in this screenshot are correct. due to a slight spelling error in the artist name between Spotify and local file system ( https://github.com/music-assistant/hass-music-assistant/issues/811 ) 

Artist search : 'salt'
![image](https://user-images.githubusercontent.com/39138434/183300232-b6cb4d47-5f95-4610-a31d-a7a45b179a76.png)

backspace and adding last letter again : 
![image](https://user-images.githubusercontent.com/39138434/183300260-a6c0edb1-9ec0-4907-bda1-b819b4a21361.png)

The results are not easy to reproduce, which suggests some kind of timing issue when processing the search text.
The second example appears to suggest that I'm getting two search results ('sal' and 'salt') as the final display result.

### Additional information

Could a 'delay' in processing the searches be the solution ?
Typing speed appears to matter in the reproduction of this issue.

### What version of Home Assistant Core are your running

 2022.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Thanks for the report. Where you have written “second example” I think you mean “first example”?

**Comment by DutchJaFO** [comment]
the 'weird' search is my first example and the 'salt' search is my second example.
The fact that 'Salma hayek' and 'Saliva' are listed when the search should be for 'salt'.
To me this suggests that I'm getting results from the search for 'sal' as well as results from the search for 'salt'

I don't have any artists with 'weir' in their names, but I suspect I'd be seeing those as 'additional' results.
This is why the second example (with 'salt' as a search text) may be a better testcase to find the source of the problem.

All of this depends on what artists are available in your library ...

**Comment by OzGav** [comment]
Yes sorry you are quite right. Will see what @marcelveldt thinks…

**Comment by DutchJaFO** [comment]
am still getting similar issues in current release

**Comment by OzGav** [comment]
Marcel says this can be fixed but is a low priority. Thanks for reporting it. This will remain open until fixed.

**Comment by OzGav** [comment]
On your second point I am about to open an issue regarding linking and minor things such as different quotation marks shouldn’t stop the link.

**Comment by OzGav** [comment]
Also please provide an update for b29 performance

**Comment by OzGav** [comment]
Mostly that looks like expected results given the linking issues. Although I see Radiohead there in the artist view which looks wrong?

**Comment by OzGav** [comment]
I personally don’t think that is right as you have selected Artist. Just because they have an album with that word doesn’t seem right to me. 
And it is the same Artist (weird Al) so it should be linked.

**Comment by OzGav** [comment]
I'm not sure I understand what you are written. As I understand how MA work the "MA library" is a pointer (if you will) to the music you have on different providers. Where it can be established that the pointer to two providers is the same thing then that is collapsed in the interface to show just one and when playing back MA chooses the highest quality. 
So where you say

> I'd argue that the search results should allow for both types of link.

I don't think that is true. MA, by design, should show only one entry ON THE MAIN PAGES for the same album/artist/track otherwise people could see up to seven entries if they had all of the current providers. The icons show that you have that thing from multiple providers. Then you can go to SHOW INFO for even greater detail. The difficulty is deciding that the thing is actually the same. Its easy if the provider supplies a unique identifier like MB ID or ISRC but not all providers do.

Radiohead I think is straight forward. "Weird" isn't in the name so it should not appear on the ARTIST view. On TOP RESULT yes it could appear as it is searching across all tags for those letters.

But we are digressing from your original issue. That being typing fast results in duplicates. This linking discussion should be in my other issue. And probably the Radiohead search result should be a discussion to see if it is expected behaviour or not.

**Comment by marcelveldt** [comment]
can you re-check this one with b59 ? At least the library now better handles this but I may also have to adjust the frontend

**Comment by OzGav** [comment]
Thanks for the follow up. The frontend will continue to be refined.
